/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package cash_register;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        CashRegister cashregister = new CashRegister();

        cashregister.start();

    }
}
